### ISSUE TITLE
Release new Tag so Module works without Cache (Serializer)

### ISSUE THREAD

**Issue by alexz707** [kokspflanze/BjyAuthorize#21]
Currently when I install the Module, the Serializer Plugin is not automatically installed by composer and throws an error.
I have seen you already have a possibility to disable the cache completely so I guess it wouldn't throw the error.

Otherwise you should add the Serializer to the dependencies in composer.

Thanks 
Regards Alex

**Comment by kokspflanze** [comment]
https://github.com/kokspflanze/BjyAuthorize/releases/tag/2.1.1

release added, i will also check to update the composer.json
