### ISSUE TITLE
Headers should be reworked

### ISSUE THREAD

**Issue by rarog** [kokspflanze/BjyAuthorize#28]
The headers are a mix of `BjyAuthorize Module (https://github.com/bjyoungblood/BjyAuthorize)` and in part even `Zend Framework (http://framework.zend.com/)` like in UnauthorizedStrategyServiceFactoryTest.php - those should either be updated or removed.
Also they mention New BSD license while the project is under MIT license.

**Comment by kokspflanze** [comment]
sry, total missed your issue=(

i will add it on my todo list

**Comment by kokspflanze** [comment]
@rarog PR created, hope its fine for you =)

**Comment by rarog** [comment]
> 
> 
> @rarog PR created, hope its fine for you =)

The PR looks good to me.
