### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by NiMeDia** [kokspflanze/BjyAuthorize#30]
Hi, thanks for keeping this library up to date!

Are there any plans on supporting PHP 8.0 in the near future?

**Comment by kokspflanze** [comment]
hi, sure but have to wait for laminas cache for the php8 supprt=(

**Comment by NiMeDia** [comment]
Oh, wow. I thought laminas was already migrated to 8.0, Thanks for the feedback!

**Comment by driehle** [comment]
@kokspflanze laminas-cache is actually already PHP 8 compatible if you ensure that some legacy storage adapters (which will not receive updates anymore) are not being installed, see https://docs.laminas.dev/laminas-cache/installation/#avoid-unused-cache-adapters-are-being-installed on how this works.

**Comment by kokspflanze** [comment]
@driehle thanks for the comment. with 2.11.0 of laminas cache they added the support of php8.

so looks good to update the package too=)

**Comment by driehle** [comment]
In `composer.json` we would need `"php": "^7.3 || ~8.0.0"` and `"laminas/laminas-cache": "^2.11.0"`, as long as the rest of BjyAuthorize is PHP8 compatible.

**Comment by kokspflanze** [comment]
@driehle not realy working=(

i updated 
````
"php": "^7.2 || ^8.0",
"laminas/laminas-cache":           "^2.11.1"
"laminas/laminas-cli":             "^1.1.1",
`````

but still laminas cache is not fully on php8

````
D:\dev\BjyAuthorize>php80 composer.phar update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-cache-storage-adapter-apc[1.0.0, ..., 1.0.1] require php ^5.6 || ^7.0 -> your php version (8.0.5) does not satisfy that requirement.
    - laminas/laminas-cache 2.11.1 requires laminas/laminas-cache-storage-adapter-apc ^1.0 -> satisfiable by laminas/laminas-cache-storage-adapter-apc[1.0.0, 1.0.1].
    - Root composer.json requires laminas/laminas-cache ^2.11.1 -> satisfiable by laminas/laminas-cache[2.11.1].
`````

so i would wait bit until they fixed it =(

**Comment by driehle** [comment]
Well, on the end of this library (i.e. when developing BjyAuthorize), you can obviously not use the replace statements as mentioned in the docs. Those have to be put in place by the end user (i.e. the user of BjyAuthorize). You'll have to use `composer install --ignore-platform-reqs` or `composer update --ignore-platform-reqs` for developing.

**Comment by kokspflanze** [comment]
i know these parameter, but im also no big fan of that stuff.

Atm you can also use the lib with `ignore-platform-reqs` to get it working on php8 and after the composer changes it will not realy change smth.
Personaly i would check to upgrade the module to laminas-cache v3 and hope they release it soon.

**Comment by NiMeDia** [comment]
I have to agree to @kokspflanze. For development/test purposes it might be ok to ignore the platform requirements but you can't provide a stable release until third-parties are fully migrated without forcing endusers to do weird stuff on install.
