### ISSUE TITLE
PHP 8 & laminas cache 3

### ISSUE THREAD

**Issue by alexz707** [kokspflanze/BjyAuthorize#36]
Hi!
any chance that you upgrade to laminas cache v3 so we could use php 8?
Regards
Alex

**Comment by kokspflanze** [comment]
Hi, 
i will check the support of laminas cache v3 on the weekend okay?

**Comment by kokspflanze** [comment]
Maybe we can also wait bit for https://github.com/laminas/laminas-authentication/pull/24

than we could add the php81 support too

**Comment by alexz707** [comment]
I'm not sure how long it takes them to release that feature - other laminas libs take ages :D
But I would say it's up to you ;)

**Comment by jroedel** [comment]
I suggest we move forward! Thanks so much for the hard work you put into
this!

**Comment by kokspflanze** [comment]
@alexz707 can you test your stuff with the following in your composer.json?

````
"kokspflanze/bjy-authorize": "dev-dependency-update as 2.3.0",
````

**Comment by kokspflanze** [comment]
laminas/laminas-authentication supports now php81 too.

i fixed some stuff with serialize, so that module supports php81 too=)

**Comment by alexz707** [comment]
Nice! I will give it a try :)

**Comment by alexz707** [comment]
So i tried it with your version and it works fine with php 8.0

Only thing I had to do was to add the following to composer:

    "laminas/laminas-cache": "^3.1",
    "laminas/laminas-cache-storage-adapter-memory": "^2.0",
    "laminas/laminas-serializer": "^2.12",

and of course activate the modules:

    'Laminas\Cache',
    'Laminas\Cache\Storage\Adapter\Memory',
    'Laminas\Serializer',

Regards Alex

**Comment by kokspflanze** [comment]
@alexz707 thanks, thats quite normal for laminas-cache3.

Just found a other bug, with the parent handling of roles, when i fixed that i will release a new version. 2.4 should be fine or?

**Comment by alexz707** [comment]
Would be perfect :)

**Comment by alexz707** [comment]
@kokspflanze: when do you release the 2.4 version? ;)

**Comment by kokspflanze** [comment]
next days, think on 3.01

**Comment by jroedel** [comment]
Awesome! v2.4 is fine with me. Count on prayers and well wishes for you this new year @kokspflanze

**Comment by kokspflanze** [comment]
@alexz707 version released
