### ISSUE TITLE
Module doesn't work with laminas/cache 2.* anymore

### ISSUE THREAD

**Issue by NiMeDia** [kokspflanze/BjyAuthorize#39]
After updating to 2.4.0 we are facing the following Issue:

> Uncaught Laminas\\ServiceManager\\Exception\\ServiceNotFoundException: Unable to resolve service "Laminas\\Cache\\Service\\StorageAdapterFactoryInterface" to a factory; are you certain you provided it during configuration? in ./vendor/laminas/laminas-servicemanager/src/ServiceManager.php:556

After digging though the changes I found that the CacheFactory was changed for laminas-cache 3.x, but it kinda breaks 2.x world.

Any meanings on this?

**Comment by NiMeDia** [comment]
So I did a bit of troubleshooting. It seems like we didn't register Laminas\Cache as a module within our application (because it wasn't neccessary before). 

You should consider adding Laminas/Cache as a module dependency.

**Comment by kokspflanze** [comment]
@NiMeDia 

sry didnt saw the issue.

yes the module dependeny is required, sry
