### ISSUE TITLE
Unable to resolve service "memory" to a factory.

### ISSUE THREAD

**Issue by jarrettj** [kokspflanze/BjyAuthorize#41]
Hey,

Good day.

Not sure how to proceed when getting this error.

Steps to reproduce:
```
# Clone laminas-mvc-skeleton
git clone https://github.com/laminas/laminas-mvc-skeleton.git
cd laminas-mvc-skeleton
# Start docker container
docker-compose up -d --build
# Install composer requirements
docker-compose run laminas composer install
# Install bjy-authorize
docker-compose run laminas composer require kokspflanze/bjy-authorize
```

Create bjyauthorize.global.php exactly as in the documentation.
Add 'BjyAuthorize' to modules.config.php.

This error surfaced in our application as well. Did the test on the skeleton to verify that it was not only our application. Any help would be appreciated, thanks in advance.

<img width="1438" alt="Screenshot 2022-04-29 at 10 50 00" src="https://user-images.githubusercontent.com/777547/165913323-5ce172a9-56a7-413c-95e2-823d09f62033.png">

Regards,
Jarrett

**Comment by kokspflanze** [comment]
Hi,

i think Laminas\Cache is missing in the module listing.

**Comment by jarrettj** [comment]
Hey man,

Good day.

It is not. Unfortunately :(.

<img width="1034" alt="Screenshot 2022-05-01 at 10 47 11" src="https://user-images.githubusercontent.com/777547/166138772-8e3b7d8a-c0cc-46bd-bab1-bf178710dc34.png">

Regards.
Jarrett

**Comment by jarrettj** [comment]
Composer file if that helps, but it is simply the skeleton + this package:

https://pastebin.com/XQgJhFYt

Regards.
Jarrett

**Comment by kokspflanze** [comment]
Hi, can you send a `composer info`

Thanks=)

**Comment by jarrettj** [comment]
Here you go, hope it helps :).

➜  laminas-mvc-skeleton composer show
brick/varexporter                         0.3.5   A powerful alternative to var_export(), which can export closures and objects without __set_state()
container-interop/container-interop       1.2.0   Promoting the interoperability of container objects (DIC, SL, etc.)
kokspflanze/bjy-authorize                 2.4.0   Laminas\Acl based firewall system for Laminas dispatch protection
laminas/laminas-authentication            2.10.1  provides an API for authentication and includes concrete authentication adapters for common use case scenarios
laminas/laminas-cache                     3.1.3   Caching implementation with a variety of storage options, as well as codified caching strategies for callbacks, class...
laminas/laminas-cache-storage-adapter-apc 1.0.1   Laminas cache adapter
laminas/laminas-component-installer       2.7.0   Composer plugin for injecting modules and configuration providers into application configuration
laminas/laminas-config                    3.7.0   provides a nested object property based user interface for accessing this configuration data within application code
laminas/laminas-development-mode          3.6.0   Laminas development mode script
laminas/laminas-escaper                   2.10.0  Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
laminas/laminas-eventmanager              3.5.0   Trigger and listen to events within a PHP application
laminas/laminas-http                      2.15.1  Provides an easy interface for performing Hyper-Text Transfer Protocol (HTTP) requests
laminas/laminas-json                      3.3.0   provides convenience methods for serializing native PHP to JSON and decoding JSON to native PHP
laminas/laminas-loader                    2.8.0   Autoloading and plugin loading strategies
laminas/laminas-modulemanager             2.11.0  Modular application system for laminas-mvc applications
laminas/laminas-mvc                       3.3.3   Laminas's event-driven MVC layer, including MVC Applications, Controllers, and Plugins
laminas/laminas-permissions-acl           2.9.0   Provides a lightweight and flexible access control list (ACL) implementation for privileges management
laminas/laminas-router                    3.5.0   Flexible routing system for HTTP and console applications
laminas/laminas-servicemanager            3.10.0  Factory-Driven Dependency Injection Container
laminas/laminas-skeleton-installer        0.6.0   Installer plugin for Laminas skeleton application
laminas/laminas-stdlib                    3.7.1   SPL extensions, array utilities, error handlers, and more
laminas/laminas-uri                       2.9.1   A component that aids in manipulating and validating » Uniform Resource Identifiers (URIs)
laminas/laminas-validator                 2.17.0  Validation classes for a wide range of domains, and the ability to chain validators to create complex validation crit...
laminas/laminas-view                      2.20.0  Flexible view layer supporting and providing multiple view layers, helpers, and more
nikic/php-parser                          v4.13.2 A PHP parser written in PHP
psr/cache                                 1.0.1   Common interface for caching libraries
psr/container                             1.1.2   Common Container Interface (PHP FIG PSR-11)
psr/simple-cache                          1.0.1   Common interfaces for simple caching
symfony/polyfill-ctype                    v1.25.0 Symfony polyfill for ctype functions
webimpress/safe-writer                    2.2.0   Tool to write files safely, to avoid race conditions
webmozart/assert                          1.10.0  Assertions to validate method input/output with nice error messages.

**Comment by kokspflanze** [comment]
@jarrettj 

can you add the memory adapter?

**Comment by jarrettj** [comment]
Yay! Much thanks @kokspflanze. Owe you bug time.

Now I am going to have to figure out why the auto injection is not working in our app :|.

Regards.
Jarrett
